### ISSUE TITLE
OpenCA Documentation

### ISSUE THREAD

**Issue by mengbin92** [openca/openca-base#6]
For my work, I want to know more inforation about OpenCA,so I found the documentation,but only got the 0.9.2,not the lastest

**Comment by spirritus** [comment]
Hey there,

your Documentation Links are broken.

OpenCA Guide (html) [https://www.openca.org/~madwolf/index.html] -> 403
OpenCA Wiki [https://www.openca.org/wiki/index.php/OpenCA_PKI_v1.1.0] -> 404 
Installing OpenCA [https://www.openca.org/wiki/index.php/Installing_OpenCA] 404
OpenCA FAQs [https://www.openca.org/wiki/index.php/OpenCA_FAQs] -> 404

Also your mail does not work, email bounced.
pki-docs@openca.org:
SMTP error from remote server for RCPT TO command, host: mail.katezarealty.com (104.168.158.213) reason: 554 5.1.1 <pki-docs@openca.org>: Recipient address rejected: User unknown 
in virtual mailbox table

Cheers
Jens
